### ISSUE TITLE
resizing discrepancy

### ISSUE THREAD

**Issue by barcavia** [hridayK/Detection-of-AI-generated-images#2]
Hi,
first of all, great work!

in the paper you mentioned:
"n alternative advantage of our approach is that the fingerprint feature extraction is robust to the size of the input image. During the common binary classifier training process, if the size of the input image is too large, users have to reduce the size of the images by downsampling. However, since the artifacts left by generative models are very weak, the downsampling operation inevitably further erases the artifacts, leading to the performance degradation of the detector. In our scheme, the size of the input image is irrelevant to the dimension of the fingerprint, which only depends on the patch size and the number of the patch."

but in fact, in your img_to_patches function, you do resize the input images:

if(img.size!=(256,256)):
        img = img.resize(size=(256,256))
        
what am I missing?

**Comment by hridayK** [comment]
A few clarifications:
- I am not the author of this paper but I have just attempted to implement the paper from the details given in the paper.
- I am resizing the images in this case because of my compute constraints, in the latest revision of the paper(as of 09/04/2024) you may read page 13 of the pdf where a patch size smaller than 32x32 would bring down the performance of the model as mentioned by the authors:
_Our approach achieves the best performance
with 32 × 32 patch size. The detection performance drops
with a small patch size._
So as the authors kept it in their paper, having images of 256x256 size with 64 patches of 32x32, I decided to stick to that and didn't try for any other image size due additional time constraints while implementing this. One can try with different image sizes though.... if you find a lower image size to be performing well, do let me know.

**Comment by Diverance** [comment]
I guess what @barcavia trying to say is : the resizing of original images before smashing it into patches might cause the erasing of artifacts,  eg, resizing a image of 768 x 768 to 256 x 256,   which is widely proved by other studies. Of course it doesn't matter if training the model with the images of 256 x 256, but when it comes to larger images, this precessing code might make the training harder.   

I think it's better to get patches of 32 x 32 directly from the original images, and randomly choose  some of the patches to form the rich and pool texture.

**Comment by hridayK** [comment]
ohhh, got the mistake. Will work on a more dynamic version of this code and push it soon. In case you wish to do so... feel free to put up a pull request

**Comment by breadxiexie** [comment]
Yes, but can Lanczos's magnification method  reduce the impact of zooming in and reducing image size?

**Comment by hridayK** [comment]
I haven't read about "Lanczos's magnification method", but will read on it, in my opinion the impact on reduction of size must not be as much of an issue. The main purpose of resizing the image was to have a uniform size for the preprocessed images for training them since the model architecture requires a fixed image size as input. I will read up more on Lanczos's magnification method and try to implement it soon if I feel it would have a significant difference on the training outcome.
